name: Deploy RabbitMQ

on:
  push:
    tags:        
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kubernetes context
        run: |
          mkdir -p ${HOME}/.kube
          echo "${{ secrets.KUBECONFIG }}" > ${HOME}/.kube/config

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Deploy RabbitMQ with Helm
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update
          helm upgrade --install rabbitmq bitnami/rabbitmq --version 15.0.6 \
            --namespace rabbitmq --create-namespace \
            --set auth.erlangCookie=${{ secrets.RABBIT_ERLANGCOOKIE }} \
            --set auth.username=${{ secrets.RABBIT_AUTHUSER }} \
            --set auth.password=${{ secrets.RABBIT_AUTHPASSWORD }} \
            --set ingress.enabled=true \
            --set ingress.path="/" \
            --set ingress.pathType=ImplementationSpecific \
            --set ingress.annotations."kubernetes\.io/ingress\.class"=traefik \
            --set ingress.annotations."cert-manager\.io/cluster-issuer"=letsencrypt-dns \
            --set ingress.hostname="${{ secrets.RABBIT_HOST }}" \
            --set ingress.tls=true \
            --set ingress.extraTls[0].hosts[0]="${{ secrets.RABBIT_HOST }}" \
            --set ingress.extraTls[0].secretName=rabbit-tls \
            --set service.type=ClusterIP
