name: Deploy phpMyAdmin

on:
  push:
    tags:        
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kubernetes context
        run: |
          mkdir -p ${HOME}/.kube
          echo "${{ secrets.KUBECONFIG }}" > ${HOME}/.kube/config

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Deploy phpMyAdmin with Helm
        run: |
          helm repo add phpmyadmin https://charts.bitnami.com/bitnami
          helm repo update
          helm upgrade --install phpmyadmin bitnami/phpmyadmin --version 18.0.0 \
            --namespace mysql \
            --set ingress.enabled=true \
            --set ingress.hostname="${{ secrets.PHPMYADMIN_HOST }}" \
            --set ingress.tls=true
