name: Deploy InfluxDB

on:
  push:
    tags:        
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kubernetes context
        run: |
          mkdir -p ${HOME}/.kube
          echo "${{ secrets.KUBECONFIG }}" > ${HOME}/.kube/config

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Deploy InfluxDB with Helm
        run: |
          helm repo add influxdb https://charts.bitnami.com/bitnami
          helm repo update
          helm upgrade --install influxdb bitnami/influxdb --version 6.3.22 \
            --namespace influxdb --create-namespace \
            --set image.debug=true \
            --set auth.admin.password=${{ secrets.INFLUXDB_PASSWORD }} \
            --set auth.admin.token=${{ secrets.INFLUXDB_ADMINTOKEN }} \
            --set auth.admin.org="${{ secrets.INFLUXDB_ORG }}"
